DjangoWebProject/DjangoWebProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tasks/', include('tasks.urls')),
    path('admin/', admin.site.urls),
]

DjangoWebProject/tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.categorized, name='categorized'),
    path('newcategory/', views.NewCategory.as_view(), name='newcategory'),
    path('newtask/', views.NewTask.as_view(), name='newtask'),
    path('<int:task_id>/details/', views.task_details, name='task_details'),
    path('<int:task_id>/close/', views.close_task, name='close_task'),
    path('<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('<int:task_id>/update/', views.UpdateTask.as_view(), name='update_task'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/<int:category_id>/delete/', views.delete_category, name='delete_category'),
    path('categories/<int:category_id>/update/', views.UpdateCategory.as_view(), name='updatecategory'),
    ]

DjangoWebProject/tasks/models.py
from django.db import models


class Category(models.Model):
	cat_name = models.CharField('Category', max_length=30)

	def __str__(self):
		return self.cat_name


class Task(models.Model):
	category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)
	name = models.CharField('Name', max_length=60)
	details = models.CharField('Details', max_length=200)
	#due_date = models.DateTimeField('Deadline')
	#date_created = models.DateTimeField(auto_now_add=True)
	is_finished = models.BooleanField(default=False)
	#date_finished = models.DateTimeField('Completion Date')
	#notes = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.name


#TODO: dodać formularze do forms.py
#TODO: dodać daty do modelu i ogarnąć je w formularzach
#TODO: zrobić ładny lay out

DjangoWebProject/tasks/forms.py
from django import forms
from .models import *


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['cat_name']


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['category', 'name', 'details', 'is_finished']

DjangoWebProject/tasks/views/base.py
from django.shortcuts import render, get_object_or_404
from tasks.models import Task, Category


def index(request):
	all_tasks = Task.objects.all()
	categories = Category.objects.all()
	context = {'all_tasks': all_tasks, 'categories': categories}
	return render(request, 'tasks/index.html', context)


def categorized(request, category_id):
	categorized_tasks = Task.objects.filter(category=category_id)
	categories = Category.objects.all()
	selected_category = Category.objects.get(pk=category_id)
	context = {'categorized_tasks': categorized_tasks, 'categories': categories, 'selected_category': selected_category}
	return render(request, 'tasks/categorized.html', context)

DjangoWebProject/tasks/views/categories.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from tasks.models import Category, Task
from django.views import View
from tasks.forms import CategoryForm
from django.db.models import Count
from django.views.generic import UpdateView


class NewCategory(View):
	def get(self, request):
		form = CategoryForm()
		categories = Category.objects.all()
		context = {'categories': categories, 'form': form}
		return render(request, 'tasks/newcategory.html', context)

	def post(self, request):
		form = CategoryForm(request.POST)
		if form.is_valid():
			category = Category.objects.create(
				cat_name=form.cleaned_data.get('cat_name')
			)
			return HttpResponseRedirect(reverse('tasks:index'))


def category_list(request):
	categories = Category.objects.annotate(num_tasks=Count('task'))
	context = {'categories': categories}
	return render(request, 'tasks/categories.html', context)


#def category_detail(request, category_id):
#	categories = Category.objects.all()
#	selected_category = Category.objects.get(pk=category_id)
#	context = {'selected_category': selected_category, 'categories': categories}
#	return render(request, 'tasks/category_detail.html', context)


def delete_category(request, category_id):
	current_category = Category.objects.get(pk=category_id)
	current_category.delete()
	return HttpResponseRedirect(reverse('tasks:category_list'))


class UpdateCategory(UpdateView):
	def get(self, request, category_id):
		categories = Category.objects.all()
		form = CategoryForm
		current_category = Category.objects.get(pk=category_id)
		context = {'categories': categories, 'current_category': current_category, 'form': form}
		return render(request, 'tasks/updatecategory.html', context)

	def post(self, request, category_id):
		categories = Category.objects.all()
		current_category = Category.objects.get(pk=category_id)
		category_name =  request.POST['new_category']
		current_category.cat_name = category_name
		current_category.save()
		context = {'categories': categories}
		return HttpResponseRedirect(reverse('tasks:category_list'))

DjangoWebProject/tasks/views/tasks.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from tasks.models import Task, Category
from django.views import View
from tasks.forms import TaskForm
from django.views.generic import UpdateView, DetailView


class NewTask(View):
	def get(self, request):
		form = TaskForm()
		categories = Category.objects.all()
		context = {'categories': categories, 'form': form}
		return render(request, 'tasks/newtask.html', context)

	def post(self, request):
		form = TaskForm(request.POST)
		if form.is_valid():
			task = Task.objects.create(
				category=form.cleaned_data.get('category'),
				name=form.cleaned_data.get('name'),
				details=form.cleaned_data.get('details'),
				is_finished=form.cleaned_data.get('is_finished')
			)
			chosen_category = Category.objects.get(cat_name=form.cleaned_data.get('category'))
			#current_cat_counter = chosen_category.task_counter
			#current_cat_counter += 1
			#chosen_category.task_counter = current_cat_counter
			chosen_category.save()
			return HttpResponseRedirect(reverse('tasks:index'))


class UpdateTask(UpdateView):
	def get(self, request, task_id):
		form = TaskForm()
		current_task = Task.objects.get(pk=task_id)
		categories = Category.objects.all()
		context = {'current_task': current_task, 'categories': categories, 'form': form}
		return render(request, 'tasks/update_task.html', context)

	def post(self, request, task_id):
		categories = Category.objects.all()
		current_task = Task.objects.get(pk=task_id)
		assigned_cat = request.POST['category_list']
		category = Category.objects.get(cat_name=assigned_cat)
		taskname = request.POST['new_task']
		taskdesc = request.POST['new_task_desc']
		current_task.category = category
		current_task.name = taskname
		current_task.details = taskdesc
		current_task.save()
		context = {'current_task': current_task, 'categories': categories}
		return HttpResponseRedirect(reverse('tasks:task_details', args=(current_task.id,)))


def task_details(request, task_id):
	selected_task = Task.objects.get(pk=task_id)
	categories = Category.objects.all()
	context = {'selected_task': selected_task, 'categories': categories}
	return render(request, 'tasks/task_detail.html', context)


def close_task(request, task_id):
	current_task = Task.objects.get(pk=task_id)
	current_task.is_finished = True
	current_task.save()
	return HttpResponseRedirect(reverse('tasks:index'))


def delete_task(request, task_id):
	current_task = Task.objects.get(pk=task_id)
	current_task.delete()
	return HttpResponseRedirect(reverse('tasks:index'))

DjangoWebProject/tasks/templates/maintemp.html
<!DOCTYPE html>
<html>
<head>
<title>My tasks</title>
<!-- Latest compiled and minified CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container-fluid">

		{% block header %}
			<h1>Tasks</h1>
			<h5>Moja pierwsza aplikacja w Django</h5>
		{% endblock %}

</div>

<nav class="navbar navbar-expand-sm bg-light">
	<div class="container-fluid">
	<ul class="navbar-nav">
		<li class="nav-item" style="margin-right:10px">
			<a href="{% url 'tasks:index' %}" class="btn btn-dark">Home</a>
		</li>
		<li class="nav-item" style="margin-right:10px">
			<a href="{% url 'tasks:newtask' %}" class="btn btn-dark">Add Task</a>
		</li>
		<li class="nav-item" style="margin-right:10px">
			<a href="{% url 'tasks:newcategory' %}" class="btn btn-dark">New Category</a>
		</li>
		<li class="nav-item" style="margin-right:10px">
			<a href="{% url 'tasks:category_list' %}" class="btn btn-dark">Category List</a>
		</li>

	</ul>
	</div>
</nav>
<div class="row">

	<div class="col-lg-2">
	
		{% block sidebar %}
			{% if categories%}
				<ul class="nav flex-column">
					{%for category in categories %}
						<li class="nav-item"><a href="{% url 'tasks:categorized' category.id %}" class="nav-link">{{category.cat_name}}</a></li>
					{%endfor %}
				</ul>
			{% else %}
				<p>No categories</p>
			{%endif %}
		{% endblock %}
	
	</div>

	<div class="col-lg-8">

		{% block content %}{% endblock %}

	</div>


</div>


</body>
</html>

DjangoWebProject/tasks/templates/tasks/categories.html
{% extends "maintemp.html" %}

{% block content %}
{% if categories %}


	<table class="table">
        <thead class="thead-dark">
		<tr>
			<th>Category name</th>
			<th>Tasks assigned</th>
		</tr>
	    </thead>
        {% for category in categories %}
        <tr>
            <td>{{category.cat_name}}</td>
            <td> {{category.num_tasks}}</td>
            <td>
                <a href="{% url 'tasks:delete_category' category.id %}" class="btn btn-primary">Delete Category</a>
                <a href="{% url 'tasks:updatecategory' category.id %}" class="btn btn-primary">Update Category</a>
            </td>
        </tr>
{% endfor %}
    </table>
{% else %}
<p>No categories</p>
{%endif %}
{% endblock %}

DjangoWebProject/tasks/templates/tasks/categorized.html
{% extends "maintemp.html" %}

{% block content %}
{% if categorized_tasks %}
<h2>Category: {{selected_category}}</h2>

<table class="table">
		<thead class="thead-dark">
		<tr>
			<th>Task Name</th>
			<th>Task Details</th>
			<th>Category</th>
		</tr>
	</thead>
		{%for task in categorized_tasks %}
  <tr>
    <td><a href="{% url 'tasks:task_details' task.id %}">{{task.name}}</a></td>
    <td>{{task.details}}</td>
    <td>{{task.category}}</td>
  </tr>

{%endfor %}
</table>
{% else %}
<p>No tasks in this category</p>
{%endif %}
{% endblock %}

DjangoWebProject/tasks/templates/tasks/category_detail.html
{% extends "maintemp.html" %}

{% block content %}


<h4>{{ selected_category.cat_name }}</h4>


<div class="btn-group">
<!--USUWANIE KATEGORII-->
	<form action="{% url 'tasks:delete_category' selected_category.id %}" method="post">
     {% csrf_token %}
     <input class="btn btn-primary" type="submit" value="Delete Category">
	</form>
</div>

{% endblock %}

DjangoWebProject/tasks/templates/tasks/index.html
{% extends "maintemp.html" %}
	{% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'tasks/bootstrap.min.css' %}">
 <script src="{% static 'tasks/bootstrap.bundle.min.js' %}"></script>

{% block content %}
{% if all_tasks %}


	<table class="table">
		<thead class="thead-dark">
		<tr>
			<th>Task Name</th>
			<th>Task Details</th>
			<th>Category</th>
			<th>Completion</th>
		</tr>
	</thead>
		{%for task in all_tasks %}
  <tr>
    <td><a href="{% url 'tasks:task_details' task.id %}">{{task.name}}</a></td>
    <td>{{task.details}}</td>
    <td>{{task.category}}</td>
	  <td>{{task.is_finished}}</td>
  </tr>

{%endfor %}
</table>
{% else %}
<p>No tasks</p>
{%endif %}
{% endblock %}

DjangoWebProject/tasks/templates/tasks/maintemp.html
<!DOCTYPE html>
<html>
<head>
<title>My tasks</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="row">

	<div class="col-sm-3">

	
	</div>

	<div class="col-sm-9">

		{% block content %}{% endblock %}

	</div>


</div>


</body>
</html>

DjangoWebProject/tasks/templates/tasks/newcategory.html
{% extends "maintemp.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Add Category</button>
</form>

{% endblock %}

DjangoWebProject/tasks/templates/tasks/newtask.html
{% extends "maintemp.html" %}

{% block content %}

<form method="post">
     {% csrf_token %}
     {{ form.as_p }}
    <button type="submit" class="btn btn-success">Add Task</button>
</form>
{% endblock %}

DjangoWebProject/tasks/templates/tasks/task_detail.html
{% extends "maintemp.html" %}

{% block content %}


<h1>{{ selected_task.name }}</h1>
<p>{{ selected_task.details }}</p>
<p>Category: {{ selected_task.category }}</p>
{#{% if selected_task.is_finished %}#}

<p>Task already finished</p>
{#{% else %}#}
<div class="btn-group">
<!--ZAMYKANIE ZADANIA-->
	<form action="{% url 'tasks:close_task' selected_task.id %}" method="post">
     {% csrf_token %}
     <input class="btn btn-primary" type="submit" value="Close task">
	</form>
	<p></p>
<!--USUWANIE ZADANIA-->
	<form action="{% url 'tasks:delete_task' selected_task.id %}" method="post">
     {% csrf_token %}
     <input class="btn btn-primary" type="submit" value="Delete task">
	</form>
	<p></p>
<!--AKTUALIZACJA ZADANIA-->
	<a href="{% url 'tasks:update_task' selected_task.id %}" class="btn btn-primary">Update Task</a>
</div>
{#{%endif %}#}
{% endblock %}

DjangoWebProject/tasks/templates/tasks/update_category.html
{% extends "maintemp.html" %}

{% block content %}

<form action="{% url 'tasks:update_category' current_category.id %}" method="post">
     {% csrf_token %}
     <fieldset>
        <legend><h2>Please change category name</h2></legend>
        <label for="category_name">Category name</label><br>
        <input type="text" id="category_name" name="new_category" value="{{current_category.cay_name}}"><br>
     </fieldset>
     <p></p>
     <input class="btn btn-success" type="submit" value="Update Category">
</form>
{% endblock %}

DjangoWebProject/tasks/templates/tasks/update_task.html
{% extends "maintemp.html" %}

{% block content %}

<form action="{% url 'tasks:update_task' current_task.id %}" method="post">
     {% csrf_token %}
     <fieldset>
        <legend><h2>Please make changes</h2></legend>
         <label for="category_list">Choose category</label><br>
         <select id="category_list" name="category_list">
             {% for cat in categories %}
             <option value="{{cat}}" >{{cat.cat_name}}</option>
             {% endfor %}
             <option value="{{current_task.category}}" selected>{{current_task.category}}</option>
         </select></br>
        <label for="task_name">Task name</label><br>
        <input type="text" id="task_name" name="new_task" value="{{current_task.name}}"><br>
        <label for="task_desc">Task description</label><br>
        <input type="text" id="task_desc" name="new_task_desc" value="{{current_task.details}}"><br>
     </fieldset>
     <p></p>
     <input class="btn btn-success" type="submit" value="Update Task">
</form>
{% endblock %}

DjangoWebProject/tasks/templates/tasks/updatecategory.html
{% extends "maintemp.html" %}

{% block content %}

<form action="{% url 'tasks:updatecategory' current_category.id %}" method="post">
     {% csrf_token %}
     <fieldset>
        <legend>Please change category name</legend>
        <label for="category_name">Category name</label><br>
        <input type="text" id="category_name" name="new_category" value="{{current_category.cat_name}}"><br>
     </fieldset>
     <p></p>
     <input class="btn btn-success" type="submit" value="Update Category">
</form>
{% endblock %}